<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_18</name>
   <tag></tag>
   <elementGuidId>73b90949-f4ec-442a-9057-48279335322d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div[3]/div/div/div/div/div/div/div[2]/div[5]/div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82ec1416-1fd4-45b3-9579-3c1a8a565920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>other-date</value>
      <webElementGuid>7bcba1b6-8bec-4989-80e6-5b7dfbb5dfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        18
                      </value>
      <webElementGuid>c97c8778-4cbc-461c-a85c-ffe5fad0072b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@class=&quot;container benefit mt-10&quot;]/div[@class=&quot;select mt-10 pt-5 pb-5 pl-10 pr-10 v-card v-sheet theme--light elevation-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;date-picker-wrapper col-sm-12 col-md-6 col-12&quot;]/div[@class=&quot;row calendar-wrap justify-space-between&quot;]/div[1]/div[@class=&quot;row fill-height&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;v-sheet theme--light&quot;]/div[@class=&quot;row justify-center&quot;]/div[@class=&quot;date-body&quot;]/div[@class=&quot;other-date&quot;]</value>
      <webElementGuid>10afe83a-51c6-4497-affc-dd7a3e9e3759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div[3]/div/div/div/div/div/div/div[2]/div[5]/div[4]/div</value>
      <webElementGuid>1b524be9-dc1c-4d51-8c2a-25ce4d72e069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[11]/following::div[21]</value>
      <webElementGuid>9e2923ee-0aad-40c6-9573-e531fedbe58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[10]/following::div[24]</value>
      <webElementGuid>1651dbb6-8c2d-4131-ae98-00a434d837e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[12]/preceding::div[12]</value>
      <webElementGuid>13118efe-9777-4879-96fd-7e1b3ae58200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[13]/preceding::div[15]</value>
      <webElementGuid>8f3174da-3818-4ffa-9e21-3129f747095d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='18']/parent::*</value>
      <webElementGuid>4fa65794-a765-46a9-a2d8-70f27a671096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/div</value>
      <webElementGuid>b2751627-346c-47a3-95ce-3e619d27f201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                        18
                      ' or . = '
                        18
                      ')]</value>
      <webElementGuid>bbc76860-05ea-4192-9d38-e2e0972051a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
