<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KOTA JAKARTA SELATAN</name>
   <tag></tag>
   <elementGuidId>5286a6b7-ca8b-492e-806f-59826a23a486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-407-3']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list-item-407-3 > div.v-list-item__content > div.v-list-item__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>80d6d624-4a71-47ec-abb2-3d261fbf2c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__title</value>
      <webElementGuid>1f8ff6b5-ece1-427a-b3b3-73127a3a2519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KOTA JAKARTA SELATAN</value>
      <webElementGuid>446bc8b0-aa61-4618-8115-c467ce6f653d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-407-3&quot;)/div[@class=&quot;v-list-item__content&quot;]/div[@class=&quot;v-list-item__title&quot;]</value>
      <webElementGuid>08cc3965-3fe0-423e-8c3e-71bf72ee449b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-407-3']/div/div</value>
      <webElementGuid>5e3f5a1b-9fc6-4422-af10-e8808a4308d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA JAKARTA PUSAT'])[1]/following::div[3]</value>
      <webElementGuid>85d351dd-3532-4caf-83cd-547158b53af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA JAKARTA BARAT'])[1]/following::div[6]</value>
      <webElementGuid>49d658b9-47c9-40d0-86e4-e7cc7e0fee22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA JAKARTA TIMUR'])[1]/preceding::div[1]</value>
      <webElementGuid>1395a8e2-624d-492e-a774-98055020d72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA JAKARTA UTARA'])[1]/preceding::div[4]</value>
      <webElementGuid>078c2a33-0f16-4912-91ea-d83d3961d711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KOTA JAKARTA SELATAN']/parent::*</value>
      <webElementGuid>12b2df5f-b5b6-4d33-b9f2-9e32d011da5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[4]/div/div</value>
      <webElementGuid>514a897f-5e7d-4e92-a63b-e823ef4baff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'KOTA JAKARTA SELATAN' or . = 'KOTA JAKARTA SELATAN')]</value>
      <webElementGuid>653b6206-c051-46a3-8593-932c3f2a5383</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
