<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Virtual Account</name>
   <tag></tag>
   <elementGuidId>00d7256c-9c82-4c7d-a999-8d9b10a0328d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[4]/div/div[2]/aside/div/div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a43fab4-48ca-4bcb-901e-03ea937aac00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-payment mt-3 v-card v-card--link v-sheet v-sheet--outlined theme--light elevation-1</value>
      <webElementGuid>a20caf3f-f300-4639-903e-6eb3b4ab10ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>124d2db0-c297-4861-b502-53316bf396bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Virtual Account </value>
      <webElementGuid>ac5a89c1-edb1-4965-8553-48648f75d9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@class=&quot;container-checkout lighten-5&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;metode-pembayaran col-md-3 col-12&quot;]/aside[1]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;mb-3 box-payment col-sm-6 col-md-12 col-12&quot;]/div[@class=&quot;card-payment mt-3 v-card v-card--link v-sheet v-sheet--outlined theme--light elevation-1&quot;]</value>
      <webElementGuid>229aaded-47f8-4b07-a4d5-63b4a50b7a16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[4]/div/div[2]/aside/div/div[4]/div</value>
      <webElementGuid>99b0f252-0258-4c5a-9f9d-412434a4acde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Kredit'])[1]/following::div[11]</value>
      <webElementGuid>78973827-cb55-450a-aa4d-934f6aa1c69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Debit'])[1]/following::div[23]</value>
      <webElementGuid>afc56c10-c183-439d-8916-f0ff055ce98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BCA'])[1]/preceding::div[8]</value>
      <webElementGuid>1c1e35b4-4c37-4bcc-b97e-17550babe51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div[4]/div</value>
      <webElementGuid>3564bfbc-c910-4bf7-b042-029db1ca3883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Virtual Account ' or . = ' Virtual Account ')]</value>
      <webElementGuid>6fdca9ea-74b9-4adf-aec4-d56271b5a7c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
