<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_17</name>
   <tag></tag>
   <elementGuidId>784818aa-9b18-4284-b271-6428c07eadc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div[3]/div/div/div/div/div/div/div[2]/div[5]/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2861562b-6dfe-45fb-ba0b-ce4d1ea85fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>other-date</value>
      <webElementGuid>8edef656-5447-476d-b8cf-10f04c40e01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        17
                      </value>
      <webElementGuid>e009a49e-7084-41ba-8250-52a11cd487f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@class=&quot;container benefit mt-10&quot;]/div[@class=&quot;select mt-10 pt-5 pb-5 pl-10 pr-10 v-card v-sheet theme--light elevation-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;date-picker-wrapper col-sm-12 col-md-6 col-12&quot;]/div[@class=&quot;row calendar-wrap justify-space-between&quot;]/div[1]/div[@class=&quot;row fill-height&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;v-sheet theme--light&quot;]/div[@class=&quot;row justify-center&quot;]/div[@class=&quot;date-body&quot;]/div[@class=&quot;other-date&quot;]</value>
      <webElementGuid>d0352537-944a-46d2-a95b-e432059d4485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div[3]/div/div/div/div/div/div/div[2]/div[5]/div[3]/div</value>
      <webElementGuid>6c0b2d4f-5efe-4b5d-a64c-580603041dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[11]/following::div[18]</value>
      <webElementGuid>5488f3ef-3295-4ade-b5a4-466cdace728f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[10]/following::div[21]</value>
      <webElementGuid>4fed7edb-781b-4217-88fe-f15d98d6b5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[12]/preceding::div[15]</value>
      <webElementGuid>34056e62-7709-4e25-b665-5ec62d8685d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[13]/preceding::div[18]</value>
      <webElementGuid>80fc5c27-dcaa-4049-8dab-bce094b5af30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='17']/parent::*</value>
      <webElementGuid>8265c727-8579-468b-8442-4da149cd979d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div</value>
      <webElementGuid>a85b6647-c067-45a6-ba8e-633f1c647080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                        17
                      ' or . = '
                        17
                      ')]</value>
      <webElementGuid>b6d6c024-b073-4882-bc6a-1df7a3abe0df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
