<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bina_v-input--selection-controls__ripple</name>
   <tag></tag>
   <elementGuidId>460b69fe-80b2-429e-a709-31fa0c26ccde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[4]/div/div[2]/div/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-input__slot > div.v-input--selection-controls__input > div.v-input--selection-controls__ripple</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>619f8739-6f72-4c6a-8c76-410867f69411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-input--selection-controls__ripple</value>
      <webElementGuid>3c5ff536-de4f-4cc9-9e7c-13f3faa05b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@class=&quot;container-checkout lighten-5&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;metode-pembayaran col-md-3 col-12&quot;]/div[@class=&quot;row mt-5 pa-5 term&quot;]/div[@class=&quot;metode-pembayaran-pernyataan col-md-12 col-12&quot;]/div[@class=&quot;v-card v-sheet theme--light&quot;]/div[@class=&quot;v-input theme--light v-input--selection-controls v-input--checkbox&quot;]/div[@class=&quot;v-input__control&quot;]/div[@class=&quot;v-input__slot&quot;]/div[@class=&quot;v-input--selection-controls__input&quot;]/div[@class=&quot;v-input--selection-controls__ripple&quot;]</value>
      <webElementGuid>478b2493-8d98-4f73-a545-b248538efde5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[4]/div/div[2]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>f49c533a-a9b8-4373-8785-71f6cbfc19b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bina'])[1]/following::div[30]</value>
      <webElementGuid>a36faa60-adae-4953-a6a8-adb88b92b55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandiri'])[1]/following::div[42]</value>
      <webElementGuid>f08c2b3e-e4b4-4f85-9560-b0b006cf6735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya telah membaca pernyataan calon nasabah serta pernyataan jenis produk.'])[1]/preceding::div[1]</value>
      <webElementGuid>2ba1c85e-a032-41ed-97cc-8947a3ea3bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bayar Sekarang'])[1]/preceding::div[4]</value>
      <webElementGuid>a7ac3b7b-4b23-4d42-af47-dda7488ae50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>56631713-2aa5-4df4-bd53-f2fad1e051dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
