<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-226</name>
   <tag></tag>
   <elementGuidId>89c5d263-00a3-4d3c-9b43-1007b24e474f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-226']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-226</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71e5f360-e77b-4b17-9220-2e2a1994bf2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return event.keyCode !== 69 &amp;&amp; event.keyCode !== 189 &amp;&amp; event.keyCode !== 190</value>
      <webElementGuid>6ac6b8b1-b279-4ca7-8616-bf4418b5976a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return /^[0-9]*$/i.test(event.key)</value>
      <webElementGuid>be6c82c3-5fab-4411-8372-e18e97c7d1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>20915d56-e9a9-4f9e-8c79-5259917c73e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-226</value>
      <webElementGuid>6b914d7b-0876-4b4a-9bda-d0217fb67e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb1e799d-25ca-4d42-9c24-26023182d4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Handphone</value>
      <webElementGuid>14652ecf-6a27-48e7-be71-0b7aa29df6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-226&quot;)</value>
      <webElementGuid>b1da2ab9-cb04-4169-8ec3-3be62e7fc747</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-226']</value>
      <webElementGuid>2e58c4b1-d93c-4bfa-a49a-10f0caeb0f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[3]/form/div[7]/div/div/div[2]/input</value>
      <webElementGuid>4ed5e306-b196-43c1-a1e9-2c23da5e659f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>cef3b87c-305d-4296-a4bd-e1c6eafd54c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-226' and @type = 'text' and @placeholder = 'Nomor Handphone']</value>
      <webElementGuid>9a7c74b8-5355-4a37-8a3a-476b637196cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
