<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Selanjutnya</name>
   <tag></tag>
   <elementGuidId>38507316-0be1-4953-88d4-22d3d74be8f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[3]/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ma-2.white--text.v-btn.v-btn--is-elevated.v-btn--has-bg.theme--light.elevation-4.v-size--x-large > span.v-btn__content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b461e959-ad19-46be-ab69-9f289f699651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn__content</value>
      <webElementGuid>f7dca711-fe9b-4e07-b85b-7dc3e8744014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Selanjutnya
        </value>
      <webElementGuid>bcb846e9-dbf0-4ccb-8f72-3a919fa698ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@class=&quot;container bg-purchase&quot;]/div[@class=&quot;form-user&quot;]/div[@class=&quot;row mr-1 ml-1 box-btn&quot;]/button[@class=&quot;ma-2 white--text v-btn v-btn--is-elevated v-btn--has-bg theme--light elevation-4 v-size--x-large&quot;]/span[@class=&quot;v-btn__content&quot;]</value>
      <webElementGuid>bbb369c9-c939-4beb-b743-6161b00f19a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[3]/div/button/span</value>
      <webElementGuid>0930a973-7d5c-43eb-8c86-5d27bcffcf67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::span[1]</value>
      <webElementGuid>e1dc59a0-eb6e-478d-8475-57df1f4bec93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[2]</value>
      <webElementGuid>97d76ae1-bb22-460c-a9e1-a3f6abb4d215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Field kesesuaian nomor whatsapp dan nomor handphone belum di pilih'])[1]/preceding::span[3]</value>
      <webElementGuid>0b1fe6f3-4793-409f-8709-01bcc0c78105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[3]</value>
      <webElementGuid>71af9e1a-3589-4cfe-b437-04db0adbebe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selanjutnya']/parent::*</value>
      <webElementGuid>785692be-482e-4014-a6e8-d3f1aac269c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>dd0a896c-3bfd-4627-a22d-0abed1b7d53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
        Selanjutnya
        ' or . = '
        Selanjutnya
        ')]</value>
      <webElementGuid>1bab52d1-aae3-4e78-b2b3-befb4dfe28b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
