<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Satu langkah lagi pembelian kamu berhasil</name>
   <tag></tag>
   <elementGuidId>17d01415-a945-485a-bfcd-81e19dccce2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div[2]/div[3]/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-center.banner-title > div.title > span.font-weight-bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a958d59a-a7a3-46d9-bbd1-72dfc5d2987a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-weight-bold</value>
      <webElementGuid>20572b4e-1fcd-4ac3-8dfb-4f2bd1198524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Satu langkah lagi pembelian kamu berhasil</value>
      <webElementGuid>7b969f28-a1a4-4e3d-9fdb-c6366efb4e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;v-image v-responsive bg-img payment-confirmation theme--light&quot;]/div[@class=&quot;v-responsive__content&quot;]/div[@class=&quot;text-center banner-title&quot;]/div[@class=&quot;title&quot;]/span[@class=&quot;font-weight-bold&quot;]</value>
      <webElementGuid>b9463e61-bd85-4993-99de-f87f3b94eaba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div[3]/div/div[2]/span</value>
      <webElementGuid>8ffc356c-9bec-40df-a2d7-2ecc19cf6688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satu langkah lagi pembelian kamu berhasil'])[1]/following::span[1]</value>
      <webElementGuid>3c8ecdf2-2af2-453c-b241-b183a28be8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali Ke Home'])[1]/preceding::span[1]</value>
      <webElementGuid>58184e48-49ee-4f83-8c81-63d99216fb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/span</value>
      <webElementGuid>d5ebac43-87e6-415e-8d8e-2474cb128293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Satu langkah lagi pembelian kamu berhasil' or . = 'Satu langkah lagi pembelian kamu berhasil')]</value>
      <webElementGuid>a12724dc-725e-464c-9b05-1c99c4b31a6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
