<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Beli Sekarang</name>
   <tag></tag>
   <elementGuidId>a50a62fb-c7b8-4313-a39a-d9246d96ac39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.d-flex.btn-buy.v-btn.v-btn--is-elevated.v-btn--has-bg.v-btn--router.theme--light.v-size--default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ba7fbc0-1a48-41c9-8230-a40580f66644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jaga-diri</value>
      <webElementGuid>6d0e1a02-6a43-4e9b-8609-0e724fb651e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex btn-buy v-btn v-btn--is-elevated v-btn--has-bg v-btn--router theme--light v-size--default</value>
      <webElementGuid>870badbc-ca26-4de1-b464-2aaf3ca67c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Beli Sekarang</value>
      <webElementGuid>32b0fe52-a58b-4d31-ada5-50417f9394cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@class=&quot;container header-wrap container--fluid&quot;]/div[@class=&quot;row header-web no-gutters&quot;]/div[@class=&quot;d-flex align-center flex-column col-sm-3 col-12&quot;]/a[@class=&quot;d-flex btn-buy v-btn v-btn--is-elevated v-btn--has-bg v-btn--router theme--light v-size--default&quot;]</value>
      <webElementGuid>a2da58af-b8b6-492b-8e71-8eb29b0007d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/a</value>
      <webElementGuid>c4767ae9-8ffa-4222-be5b-dc0bd1dccc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara Klaim'])[2]/following::a[1]</value>
      <webElementGuid>1de4fc7c-943e-4061-842a-55b34e6eec85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proteksi Jagahujan'])[2]/following::a[2]</value>
      <webElementGuid>d4ca7959-805d-4205-9992-368d315d1dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manfaat Perlindungan'])[1]/preceding::a[2]</value>
      <webElementGuid>d3454208-18fc-46b7-b15e-2b46bbe10e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/jaga-diri')]</value>
      <webElementGuid>f424a6cb-5967-4656-b76d-de4ee24ec742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>6ac09a57-dcf4-4ca5-8011-a041ea9cc3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/jaga-diri' and (text() = ' Beli Sekarang' or . = ' Beli Sekarang')]</value>
      <webElementGuid>f35a7be0-8a09-4170-8667-8d9a56f394d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
